name: "JFROG CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          curl -L -u${{ secrets.JF_USER }}:${{ secrets.JF_ACCESS_TOKEN }} -T file.txt "${{ secrets.JF_URL }}/artifactory/liorm-generic-local/file.txt" 
