name: "JFROG CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: |
	  curl -L -uvoyagers2:${{ secrets.JF_ACCESS_TOKEN }} -T ../../file.txt "${{ secrets.JF_URL }}/artifactory/liorm-generic-local/liorm.txt" 
